JD_SCHEMA = {
    "job_title": None,
    "company_name": None,
    "preferred_candidate_location": None,
    "maximum_experience_years": 0,
    "required_skills": [],
    "good_to_have_skills": [],
    "required_experience_years": 0,
    "required_education": [],
    "responsibilities": [],
    "location": None,
    "mode": None,
    "salary": None,
    "notice_period": None,
    "employment_type": None,
    "contract_to_hire": False,
    "certifications": [],
    "languages": [],
}
