RESUME_SCHEMA = {
    "name": None,
    "email": None,
    "phone": None,
    "location": None,
    "preferred_location": None,
    "current_location": None,
    "address": None,
    "permanent_address": None,
    "current_position": None,
    "target_role": None,
    "total_experience_years": 0,
    "skills": [],
    "education": [],
    "certifications": [],
    "languages": [],
    "expected_salary": None,
    "notice_period": None,
    "employment_type": None,
    "projects": [],
    "work_experience": [],
}